### ISSUE TITLE
ValueError: Namespace Vte not available

### ISSUE THREAD

**Issue by 866666** [needle-wang/sqlmap-gtk#7]
Traceback (most recent call last):
  File "/sqlmap/sqlmap_gtk.py", line 10, in <module>
    from widgets import (GLib, Vte, d, g, Box, Frame, btn, label)
  File "/sqlmap/widgets.py", line 12, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
kali 报错 缺什么包么

**Comment by needle-wang** [comment]
sudo apt-get install gir1.2-vte-2.91

**Comment by 866666** [comment]
您发给我的邮件已经被收到
