### ISSUE TITLE
报错如下

### ISSUE THREAD

**Issue by H-Kii** [needle-wang/sqlmap-gtk#8]
Traceback (most recent call last):
  File "/root/sql_gui/sqlmap-gtk/./sqlmap_gtk.py", line 10, in <module>
    from widgets import (GLib, Vte, d, g, Box, Frame, btn, label)
  File "/root/sql_gui/sqlmap-gtk/widgets.py", line 9, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by needle-wang** [comment]
has gtk3 been installed?
dpkg -l | grep libgtk-3

try this:
apt-get install python3-gi
